<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_welcome_p-inputtext p-component p-fil_46a565_1</name>
   <tag></tag>
   <elementGuidId>163c7806-47ec-438c-9a31-4384dda6ce5b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.p-input-icon-left.w-full.relative > input.p-inputtext.p-component.p-filled.w-full.w-full</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>36d2f574-7111-4e01-abae-aa991979dc06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-inputtext p-component p-filled w-full w-full</value>
      <webElementGuid>d84b0863-6c1a-4ab0-920b-fec1185c188e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>3cf9ccc3-2dbb-4cd2-a736-4c71d113b9b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>4ee63f9f-e6c1-4ab9-bebc-81d4b3293c73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;login-container flex h-screen p-8&quot;]/div[@class=&quot;login-form col-6 flex justify-content-center align-items-center flex-column relative&quot;]/div[@class=&quot;login-form__with-username text-center w-6 fadeinright animation-duration-300 animation-iteration-1 animation-linear&quot;]/form[@class=&quot;p-fluid&quot;]/div[@class=&quot;field col-12 relative&quot;]/span[@class=&quot;p-input-icon-left w-full relative&quot;]/input[@class=&quot;p-inputtext p-component p-filled w-full w-full&quot;]</value>
      <webElementGuid>19110438-f5ae-4450-9641-13796ca9dcfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ae7484c7-f706-4c28-a499-58f409b0035a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-inputtext p-component p-filled w-full w-full</value>
      <webElementGuid>0cae9107-d7cb-4fe5-8dd7-937c1aa9a99a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>613edad9-4cdf-4700-a4f2-764f73dc65ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>72c7e602-a5a1-4532-bbb2-b174b6c083f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;login-container flex h-screen p-8&quot;]/div[@class=&quot;login-form col-6 flex justify-content-center align-items-center flex-column relative&quot;]/div[@class=&quot;login-form__with-username text-center w-6 fadeinright animation-duration-300 animation-iteration-1 animation-linear&quot;]/form[@class=&quot;p-fluid&quot;]/div[@class=&quot;field col-12 relative&quot;]/span[@class=&quot;p-input-icon-left w-full relative&quot;]/input[@class=&quot;p-inputtext p-component p-filled w-full w-full&quot;]</value>
      <webElementGuid>352ca8b6-3e90-4f69-9717-b445d5f14b4c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='password']</value>
      <webElementGuid>afd7d0f6-264b-4e1c-8f80-f7833ca77c9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[2]/div[2]/div[2]/form/div[2]/span/input</value>
      <webElementGuid>826ba860-d080-4913-8518-ca410702a1d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span/input</value>
      <webElementGuid>71ae8123-b744-444f-bb53-6c107867193a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @placeholder = 'Password']</value>
      <webElementGuid>a8997196-acbd-4c3f-bc02-64ffc5c327de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[2]</value>
      <webElementGuid>e4efb7a3-fe5f-4ddd-9249-ea0862f065ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Password']</value>
      <webElementGuid>abb78954-a86c-4da5-81de-65c86c792b7d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
