<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Mina1</name>
   <tag></tag>
   <elementGuidId>39986bd1-c068-45db-87c1-e7a97959b219</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='client-table']/tbody/tr/td[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e14f4d18-004a-4f94-8ee2-6899c60e0a7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://rise.fairsketch.com/clients/view/146</value>
      <webElementGuid>b5f51ce4-925d-4c41-b6f1-34eede0f0abb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mina1</value>
      <webElementGuid>fee86438-2942-4dd8-b658-87a0b1d4cfa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;client-table&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[@class=&quot;all&quot;]/a[1]</value>
      <webElementGuid>6fd0f415-d82b-42d3-ad78-239d6df0c858</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='client-table']/tbody/tr/td[2]/a</value>
      <webElementGuid>26c35eba-fbe2-4870-af3d-f5584a617614</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Mina1')]</value>
      <webElementGuid>08e62ee9-4c28-48de-add7-cd0619bad098</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Due'])[1]/following::a[1]</value>
      <webElementGuid>57f5ec95-52c4-448d-a2d7-1a165d25be27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payment Received'])[1]/following::a[1]</value>
      <webElementGuid>919d71d9-2d97-4aa2-a307-b686b87ec398</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VIP'])[2]/preceding::a[1]</value>
      <webElementGuid>7b355075-413a-4ddf-b93a-30664dcba491</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$0.00'])[1]/preceding::a[1]</value>
      <webElementGuid>eeba44b5-6edf-4ddf-8c8a-22ab50310393</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Mina1']/parent::*</value>
      <webElementGuid>94b001c9-b414-45e9-9bbe-10ff4425345e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://rise.fairsketch.com/clients/view/146')]</value>
      <webElementGuid>171c2524-ed8c-472a-a7d8-9700c585d5ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/a</value>
      <webElementGuid>f67b818d-4639-4031-a265-19f6921d865a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://rise.fairsketch.com/clients/view/146' and (text() = 'Mina1' or . = 'Mina1')]</value>
      <webElementGuid>3d1ab297-adb1-4f73-a41e-44e6f1e40bcc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
