<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_VAT Number_vat_number</name>
   <tag></tag>
   <elementGuidId>72f0d044-f9a0-4474-bd97-2c9a30cebf9f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#vat_number</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='vat_number']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9a333807-0cf2-4d05-a787-b7db27e86ff6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8f5a0231-c5d8-4819-89d8-910178abc31c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>vat_number</value>
      <webElementGuid>ae0b5ef1-9ef8-4b41-a724-1a37bcf2b6ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>vat_number</value>
      <webElementGuid>8cd4f9a4-9abf-4011-b960-c9e7ba88aed4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>ca58bf9e-6abd-4ff8-a45b-4036c48360cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>VAT Number</value>
      <webElementGuid>4eb3fb6b-eecd-4056-a917-809960117715</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vat_number&quot;)</value>
      <webElementGuid>3ee8551f-7b0c-4b4d-b676-306b2c032e2d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='vat_number']</value>
      <webElementGuid>234111cf-7f05-46b7-8c01-2e28b12f5c52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='oqsvxdfh']/div/div[11]/div/div/input</value>
      <webElementGuid>58c8c671-62fc-4974-a7be-98f484a592b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div/input</value>
      <webElementGuid>449bc5fb-df49-4b50-9fdf-0f660bcd48ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'vat_number' and @id = 'vat_number' and @placeholder = 'VAT Number']</value>
      <webElementGuid>aad532f0-0feb-4ce0-b5ba-b37d51e01e6a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
