<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Zip_zip</name>
   <tag></tag>
   <elementGuidId>aa283991-c13a-4293-b8c4-41b2af64d15a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#zip</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='zip']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>73a4750c-8d84-496d-830e-c84218dce36f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>87954d57-b2db-4ffc-81c9-d2ae6ab33120</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>zip</value>
      <webElementGuid>3548c0dd-091d-47fe-b67d-26413b15d9a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>zip</value>
      <webElementGuid>67d80fe5-bdd9-4bc9-9bec-a158b8434a7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>8e9fa337-fa4b-416d-9f37-819abe875a5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Zip</value>
      <webElementGuid>e88d92bd-1114-4012-9d6d-33aa098fc248</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;zip&quot;)</value>
      <webElementGuid>51da2933-af73-447a-ba90-42f46997c257</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='zip']</value>
      <webElementGuid>cb112ebf-c379-43a7-b19c-8f1c99c58cbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='oqsvxdfh']/div/div[7]/div/div/input</value>
      <webElementGuid>822772ff-b2d7-4538-af8a-ecbe60ff5901</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/input</value>
      <webElementGuid>204ccfd3-8d9c-478d-8fcf-394c692f7404</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'zip' and @id = 'zip' and @placeholder = 'Zip']</value>
      <webElementGuid>7a6c2767-4d27-4b67-b3f5-5d07a3ea95e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
