<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Website_website</name>
   <tag></tag>
   <elementGuidId>12abb506-ef43-46e2-a06e-094bbd232649</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#website</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='website']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>542015c2-d485-4a30-802f-37107315009e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>746d6ef2-8d96-425b-a8c5-1281b2ef5fda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>website</value>
      <webElementGuid>72a1f6d8-b423-4e6c-aa62-a2294368755a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>website</value>
      <webElementGuid>26b9d125-9d49-47a7-bc51-b2034ac5ea15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>16fed6a3-9e88-4b55-a05b-cf2e49b79dcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Website</value>
      <webElementGuid>647134ea-7c56-40dd-989a-9d4c5bebb07e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;website&quot;)</value>
      <webElementGuid>37aeac3f-9192-481a-a91b-9ae6f46163cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='website']</value>
      <webElementGuid>c81e026c-fedc-42c8-b171-3c3ac5d69549</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='oqsvxdfh']/div/div[10]/div/div/input</value>
      <webElementGuid>d972ba97-c828-4063-9803-3d5ea88ee372</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div/input</value>
      <webElementGuid>db969b09-bf7e-45d1-9f6e-f55bc0411ae6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'website' and @id = 'website' and @placeholder = 'Website']</value>
      <webElementGuid>2d880846-428c-4fd3-aba3-378c4ca57563</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
